### PR TITLE
Fix `input` vertical spacing

### PR DESCRIPTION
**Pull request by FlyersPh9**
## Changes

- Fix vertical spacing within `<input>` by reverting https://github.com/iTwin/iTwinUI/pull/1270/files?file-filters%5B%5D=.html&file-filters%5B%5D=.md&file-filters%5B%5D=.scss&show-viewed-files=true#diff-4623585aa5d420e8e06bbb618dd09a22a22d7946948cd311def55eaa7a64e9a0.

## Testing

- Visual tests.

## Docs

N/A

### CODE REVIEW

**Comment by LostABike** [comment]
It seems there is a conflict to be resolved. I also checked this out locally, there is just a 1px difference from prod branch? Which...is probably fine to me lol, but not sure what others think. (left side is this branch)
image

**Comment by LostABike** [comment]
> It seems there is a conflict to be resolved. I also checked this out locally, there is just a 1px difference from prod branch? Which...is probably fine to me lol, but not sure what others think. (left side is this branch) image

http://localhost:6006/?path=/story/input-select--basic

**Comment by FlyersPh9** [comment]
> It seems there is a conflict to be resolved. I also checked this out locally, there is just a 1px difference from prod branch? Which...is probably fine to me lol, but not sure what others think. (left side is this branch) image

Good catch! I have fixed it visually, but the fix doesn't feel great to me.

**Comment by LostABike** [comment]
The input seems good now. Another thing that is slightly off-centered for me is the radio, you can compare the two here:
https://itwin.github.io/iTwinUI/1310/react/?path=/story/input-radio--basic
https://itwin.github.io/iTwinUI/react/?path=/story/input-radio--basic

But again, pretty minor 😅

**Comment by FlyersPh9** [comment]
> The input seems good now. Another thing that is slightly off-centered for me is the radio, you can compare the two here: [itwin.github.io/iTwinUI/1310/react/?path=/story/input-radio--basic](https://itwin.github.io/iTwinUI/1310/react/?path=/story/input-radio--basic) [itwin.github.io/iTwinUI/react/?path=/story/input-radio--basic](https://itwin.github.io/iTwinUI/react/?path=/story/input-radio--basic)
> 
> But again, pretty minor 😅

This is fixed as well.  Thank you for catching these @LostABike!  I still feel the same as I said [here](https://github.com/iTwin/iTwinUI/pull/1310#issuecomment-1571033022) tho:
> the fix code wise doesn't feel great to me.

**Review by gretanausedaite — APPROVED** [review]

**Review by LostABike — APPROVED** [review]
Everything is centered for me now 😄

**Comment by mayank99** [comment]
for the three failing react tests (ComboBox, Select, Breadcrumbs), try to use the images from CI artifacts instead of approving locally. there's a zip file that gets uploaded for each [run](https://github.com/iTwin/iTwinUI/actions/runs/5223410536?pr=1310).

**Pull request merged**
