### PR TITLE
chore: Add Open Sans to demo pages

### PR DESCRIPTION
**Pull request by gretanausedaite**
- Add `Open Sans` to demo pages
- Update test images

Changed components (size because of font change):
- Badge
- Buttons
- Carousel (inner content on first slide)
- Fieldset
- Side nav
- Skip to content

### CODE REVIEW

**Review by veekeys — APPROVED** [review]
There are some width changes in certain elements (or even height?) Might be interesting to see if some of our components got broken.. But reviewing 400 images is too much, so hopefully will notice as we go.

**Comment by mayank99** [comment]
This is not a feature that we are releasing in the package, so `feat` shouldn't be used

**Comment by gretanausedaite** [comment]
> This is not a feature that we are releasing in the package, so `feat` shouldn't be used

chore?

**Comment by FlyersPh9** [comment]
> There are some width changes in certain elements (or even height?) Might be interesting to see if some of our components got broken.. But reviewing 400 images is too much, so hopefully will notice as we go.

@veekeys that might be a result of the Open Sans font being slightly larger/smaller than whatever font was being loaded previously.

**Pull request merged**
