### PR TITLE
chore: v1 branch

### PR DESCRIPTION
**Pull request by mayank99**
This draft PR will help run CI on each commit and also provide the "Update branch" button.

Live preview at: https://itwin.github.io/iTwinUI/639

### CODE REVIEW

**Comment by mayank99** [comment]
@adamhock Can you push your last change to a new branch instead of here?

**Comment by mayank99** [comment]
@gretanausedaite The v1 deploy doesn't seem to be working 😦

**Comment by veekeys** [comment]
## (2022-06-07)

- **Alert:** Class name & specificity refactor [commit](https://github.com/iTwin/iTwinUI/pull/639/commits/6efd8e5f93ed57867287dd632b7b93899b2b730b)
	- `iui-button iui-borderless iui-small` -> `iui-alert-button`
	- `iui-button-icon` -> `iui-alert-button-icon`
	- `iui-alert iui-informational` -> `iui-alert-informational` (same with all the statuses)
- **Inputs:** Inputs moved to separate folders [commit](https://github.com/iTwin/iTwinUI/pull/639/commits/feaef5338b599e4c055791adac74e371dee36e42)
	- `@itwin/itwinui-css/css/checkbox.css`
	- `@itwin/itwinui-css/css/input-container.css`
	- `@itwin/itwinui-css/css/input.css`
	- `@itwin/itwinui-css/css/radio.css`
	- `@itwin/itwinui-css/css/select.css`
	- `@itwin/itwinui-css/css/textarea.css`
	- Might be important to check if any react components might need combo of imports now
- **Cleanup z-index:** Some components got z-index removed. Should not influence anything [commit](https://github.com/iTwin/iTwinUI/pull/639/commits/8435f0aaa001f5a8255b1cf5ee3b6c73a1bf3e01)
- **Components renamed:** Path of imports changed accordingly [commit](https://github.com/iTwin/iTwinUI/pull/639/commits/d8d5f8d213cb4bed0b7191c9a62590621723c47d)
	- `user-icon` -> `avatar`
	- `wizard` -> `stepper`
	- `toast-notification` -> `toast`
- **Mixin `themed` got removed:** Dropped IE support, instead using css variables [commit](https://github.com/iTwin/iTwinUI/pull/639/commits/a1ae5fc570a2e223a26ba6a6072a1eb84647ac0d)
- **`resetGlobalStyles` is removed.`** Can use `iui-reset` mixin for simple reset values or take bigger one from web. [commit](https://github.com/iTwin/iTwinUI/pull/639/commits/a1ae5fc570a2e223a26ba6a6072a1eb84647ac0d)

**Comment by gretanausedaite** [comment]
- **Typography**: Changed font family to `Noto Sans` [commit](https://github.com/iTwin/iTwinUI/commit/66957dde831bd2edeb8135887431e537d5f0664d)

**Comment by veekeys** [comment]
@elephantcatdog More information would be useful to have on the `border-box` changes as:
- What components were visually influenced (I remember you did change the header size, what else?)
- What could be the risks for the user after this change (Maybe somewhere users were explicitly overriding the border-box rule, for example.. and what else? Issues you have faced with demos could be examples too)
- There was a new addition to the user icons size? Might want to add in react too. So it is worth mentioning in here.

The purpose of these additional comments is to help ourselves migrate react, also deliver a proper changelog to the users. Otherwise, after we are done with all of these, we will need to come back to commits and try to review all over again to figure the exact changes. It is just easier to put all you remember now, while its fresh :)

**Comment by elephantcatdog** [comment]
<b>Radio Tile:</b> Fixed border issues with stacking radio tiles. Fixed tooltip usage on radio tiles. commit

**Comment by veekeys** [comment]
- **Folder structure review**: Some files changed their path and names [commit](https://github.com/iTwin/iTwinUI/commit/84ee35e95a6dcb1098a1b4d3614e98a9f42a1313)
  - `anchor` was moved away from global styles (and styles folder)
  -  `styles/variables` -> `style/global-variables`
  - `icon/variables` -> `style/icons-sizes`
  - `styles/ripple` -> `utils/mixins`
  - `styles/mixins` -> `utils/mixins`
  - `input-container` -> `utils/input-container` 
  - `notification-marker` -> `utils/notification-marker` 
  - `popover` -> `utils/popover`
  
  Someones verification would be helpful, if I havent missed anything

**Comment by FlyersPh9** [comment]
## #684 changes

### Button variants & types

- `<button class="iui-button iui-default">` -> `<button class="iui-button">`
- `<button class="iui-button iui-high-visibility">` -> `<button class="iui-button" data-iui-variant="high-visibility">`
- `<button class="iui-button iui-cta">` -> `<button class="iui-button" data-iui-variant="cta">`
- `<button class="iui-button iui-borderless">` -> `<button class="iui-button" data-iui-variant="borderless">`
- `<button class="iui-button iui-idea">` -> `<button class="iui-button" data-iui-variant="idea">`
- `<button class="iui-button iui-dropdown">` -> `<button class="iui-button iui-button-dropdown">`

### Button sizes

- `<button class="iui-button iui-small">` -> `<button class="iui-button" data-iui-size="small">`
- `<button class="iui-button iui-large">` -> `<button class="iui-button" data-iui-size="large">`

### Active button state

- `<button class="iui-button iui-active">` -> `<button class="iui-button" data-iui-active="true">`

### Disabled button states

```diff
<button disabled>
<button disabled="disabled">
+ <button aria-disabled="true">
```

### Button label

- `<span class="iui-button-label">Hello</span>` -> `<span>Hello</span>"`

### Split menu

- `<span class="iui-button-split-menu">` -> `<span class="iui-button-split">`

**Comment by FlyersPh9** [comment]
## #698 changes

### Stepper wrapper

- `<div class="iui-stepper iui-long">` -> `<div class="iui-stepper">`

### Workflow diagram HTML structure changes

Before:

```html
<div class="iui-stepper iui-workflow">
  <ol>
    <li class="iui-stepper-step">
      <div class="iui-stepper-track-content">
        <span class="iui-stepper-circle">Start</span>
      </div>
    </li>
  </ol>
</div>
```

After:

```html
<ol class="iui-workflow-diagram">
  <li class="iui-workflow-diagram-step">
    <span class="iui-workflow-diagram-content">Start</span>
  </li>
</ol>
```

**Comment by adamhock** [comment]
### Table Refactor #697 

- **Data Attribute**
  - `iui-condensed/extra-condensed` replaced with `data-iui-size="condensed/extra-condensed"`
  - `iui-extra-condensed` replaced with `data-iui-size="extra-condensed"`
  - `iui-selected` changed to `aria-selected="true"`
    - `iui-table-body` elements that contain selectable rows now have `aria-multiselectable="true"`
  - `iui-positive/negative/warning` replaced with `data-iui-status="positive/negative/warning"`
  - `iui-disabled` replaced with `aria-disabled="true"`
- **Class name changes**
  - `iui-paginator-*` changed to `iui-table-paginator-*`
  - `iui-column-filter` changed to `iui-table-column-filter`
  - `iui-filter-button` changed to `iui-table-filter-button`
  - `iui-resizer-*` changed to `iui-table-resizer-*`
  - `iui-sort` changed to `iui-table-sort`
  - `iui-reorder-bar-*` changed to `iui-table-reorder-bar-*`
  - `iui-more-options` changed to `iui-table-more-options`
  - `iui-expanded-content` changed to `iui-table-expanded-content`
- **Other**
  - Reduced `condensed.scss` and `extra-condensed.scss` to `sizes.scss`
  - `iui-row` separated into its own mixin

**Comment by FlyersPh9** [comment]
## #640 changes

- `.iui-left` -> `.iui-page-header-left`
- `.iui-center` -> `.iui-page-header-center`
- `.iui-right` -> `.iui-page-header-right`


- `.iui-header-logo` -> `.iui-header-brand`
- `.iui-header-button-icon` -> `.iui-header-brand-icon`
- `.iui-label` -> `.iui-header-brand-label`


- `.iui-divider` -> `.iui-page-header-divider`


- `<nav>` -> `.iui-header-breadcrumbs`
- Add `<ol class="iui-header-breadcrumbs-list">`.
- Add `<li class="iui-header-breadcrumb-item">`.
- `class="iui-button iui-header-button iui-header-dropdown-button" data-iui-variant="borderless"` -> `.iui-header-breadcrumb-button`.
- `class="iui-button-icon iui-header-button-icon` -> `.iui-header-breadcrumb-button-icon`.

```diff
- <span>
- 	<div>Label</div>
- 	<div class="iui-description">Sublabel</div>
- </span>
+ <span class="iui-header-breadcrumb-button-text">
+ 	<span class="iui-header-breadcrumb-button-text-label">Label</span>
+ 	<span class="iui-header-breadcrumb-button-text-sublabel">Sublabel</span>
+ </span>
```

- `.iui-button-icon` -> `.iui-header-breadcrumb-button-dropdown-icon`.

```diff
- <svg-chevron-right class="iui-chevron"></svg-chevron-right>
+ <li class="iui-breadcrumbs-separator">
+ 	<svg-chevron-right></svg-chevron-right>
+ </li>
```

**Comment by elephantcatdog** [comment]
<b>Icon:</b> Refactored and separated icon color from icon size [commit](https://github.com/iTwin/iTwinUI/commit/684f4f1ec350e8f2b3152c171e2bb78a6a84f5a3)
- Changed icon descriptors from using `icons` to using `icon`
- Icon folder moved to `utils` folder
- Icon size and color mixins take args
- Size mixin labels match that of other places (s, m, l, xl, 2xl, and 3xl)
- Icon classes changed to use data attributes for both size and color

**Comment by mayank99** [comment]
- `.scss` files are no longer included the published package ([#745](https://github.com/iTwin/iTwinUI/pull/745))

**Comment by mayank99** [comment]
- `iui-textarea` has been removed and replaced by `iui-input` ([#743](https://github.com/iTwin/iTwinUI/pull/743))

**Comment by mayank99** [comment]
- Updated border-radius of remaining components to 4px ([#746](https://github.com/iTwin/iTwinUI/pull/746))

**Comment by mayank99** [comment]
- `iui-visually-hidden` has been moved from global.css to utils.css ([#639](https://github.com/iTwin/iTwinUI/pull/639))

**Comment by mayank99** [comment]
- Replaced `iui-body` with new `iui-root` class to allow scoping iTwinUI styles. ([#749](https://github.com/iTwin/iTwinUI/pull/749))

**Comment by mayank99** [comment]
- Updated all components to use `@itwin/itwinui-variables` instead of Sass variables ([#718](https://github.com/iTwin/iTwinUI/pull/718))
- `iui-input` and `iui-select-button` now require sizes to be passed as data attributes. ([#718](https://github.com/iTwin/iTwinUI/pull/718))
  - `iui-small` becomes `data-iui-size='small'`, `iui-large` becomes `data-iui-size='large'`

**Comment by FlyersPh9** [comment]
## #719 split button changes

### Removal of wrapping `<div>`

```diff
<span class="iui-button-split">
- <div>
     <button />
- </div>
- <div>
     <button />
- </div>
</span>
```

**Comment by FlyersPh9** [comment]
## #620 `/input/` changes

Break `/inputs/` into multiple folders:
- `/checkbox/`
- `/input/`
- `/label/`
- `/radio/`
- `/select/`

**Comment by FlyersPh9** [comment]
## #740 menu changes

Introduced `var(--iui-menu-max-height)` within `.iui-scroll` modifier class with a default value of 315px.  This can be set by the user.

**Comment by mayank99** [comment]
Closing this as it's superseded by https://github.com/iTwin/iTwinUI/pull/756. Everyone please verify and copy over your changelog (including all and _only_ user-affecting changes) to https://github.com/iTwin/iTwinUI/wiki/v1-Migration-guide.

**Pull request closed without merging**
