### PR TITLE
Make vite server workspaces' dev script persistent in turbo

### PR DESCRIPTION
**Pull request by rohan-kadkol**
## Changes

After #1826, upon running `yarn dev` from the root, I noticed that the vite servers (`vite-playground` and `css-workshop`) were not started. Upon starting only those servers using [`--filter`](https://turbo.build/repo/docs/core-concepts/monorepos/filtering), I realized that the turbo command was just ending even though there were no errors.

So, this PR just adds [`persistent: true`](https://turbo.build/repo/docs/reference/configuration#persistent) to `vite-playground#dev` & `css-workshop#dev`.

|Before|With this PR|
|-|-|
|image<br/>Ending by itself|image<br />Ending only after <kbd>Ctrl</kbd> + <kbd>C</kbd>|

Related: https://github.com/vercel/turbo/issues/6272

## Testing

* Confirmed that the vite-playground and the css-workshop now open upon running `yarn dev` from the root.

## Docs

N/A

### CODE REVIEW

**Review by Ben-Pusey-Bentley — COMMENTED** [review]
I haven't been able to recreate the original issue that this PR is addressing. Can you still reproduce it in the current main?

**Comment by rohan-kadkol** [comment]
> Can you still reproduce it in the current main?

Yes, with the current `main` checked out, the vite-playground and the css-workshop aren't running when I visit the respective URLs.

> I haven't been able to recreate the original issue that this PR is addressing.

Ohh, to confirm, after you run `yarn dev` from the root repo folder, are the workspaces' dev servers running for you when you visit these URLs?
* vite-playground: http://localhost:1701/
* css-workshop: http://localhost:5173/

**Comment by Ben-Pusey-Bentley** [comment]
> Ohh, to confirm, after you run `yarn dev` from the root repo folder, are the workspaces' dev servers running for you when you visit these URLs?
> 
> * vite-playground: http://localhost:1701/
> * css-workshop: http://localhost:5173/

Yes, after I run `yarn dev`, both of those dev servers are running.

**Review by mayank99 — APPROVED** [review]
LGTM 👍

I feel like all dev servers should be persistent, but I don't want to spend too much time fiddling with this if it works.

**Review by Ben-Pusey-Bentley — APPROVED** [review]
Yeah, this branch works fine as well on my end. Just had some questions because I couldn't reproduce.

**Pull request merged**
