### PR TITLE
fix vite config for windows

### PR DESCRIPTION
**Pull request by mayank99**
## Changes

windows build was failing because of returning invalid paths.

this is what happens when you trust code written by copilot. 🙃

changed `__dirname` to use `fileURLToPath` and changed `path.resolve` to `path.join`.

## Testing

Tested on:
- [x] macbook
- [x] CI (linux)
- [x] windows (tested by @LostABike and also in #1339)

## Docs

N/A

### CODE REVIEW

**Review by adamhock — APPROVED** [review]

**Comment by mayank99** [comment]
@adamhock Did you test this locally?

**Comment by adamhock** [comment]
> @adamhock Did you test this locally?

Sorry for the premature approval 😅. The build is still failing on Windows with the same issue

**Review by LostABike — APPROVED** [review]
Awesome, all builds work for me now 🎉

**Review by adamhock — COMMENTED** [review]
All builds work for me as well! Will approve once all tests pass just to be safe

**Pull request merged**
