### PR TITLE
refresh site colors

### PR DESCRIPTION
**Pull request by mayank99**
## Changes

Small visual refresh of the website with a focus on making the colors feel more sophisticated.
- Darker, less blue backgrounds, and fewer gradients.
  - The tokens are set up with a `themeVar` Sass mixin, to enable easier creation of light theme in a future PR.
- More readable code snippets with adjusted font size and a more neutral [`github-dark`](https://vscodethemes.com/e/github.github-vscode-theme/github-dark?language=javascript) theme.
- Adjusted fluid typography to work better on smaller widths.
- Isolated demos using [`revert-layer`](https://developer.mozilla.org/en-US/docs/Web/CSS/revert-layer). Website styles will no longer affect component demos.
- Postprocessing using [`lightningcss`](https://lightningcss.dev/). (Previously we weren't adding vendor prefixes, etc.)
- Small minor fixes here and there.

Still lots more to improve (I wanted to play with text colors) but running out of time. Always can be improved in future PRs.

## Testing

See [deploy preview](https://deploy-preview-1751--itwinui-previews.netlify.app/).

## Docs

N/A. No package changes.

### CODE REVIEW

**Comment by FlyersPh9** [comment]
On the landing page:
- Documentation button likely isn't passing contrast.
- The "copy" icon should probably use `currentColor`.

image


Aside from that, looks good to me.  I like that there are fewer lines / borders thru out.

**Comment by mayank99** [comment]
your local setup might be messed up. this is what the deploy preview looks like:

**Comment by FlyersPh9** [comment]
Yeah, something is definitely messed up.  Now it looks like this:
Screenshot 2023-12-27 at 5 43 30 PM

Will look into it tomorrow.

**Comment by FlyersPh9** [comment]
Revisited this today.  I tried the test deploy & pulled locally to build but both are still showing the white text in the documentation button.  I did a little poking around and I think it has to do with the theme of the OS.  I am in light theme (problem is present) but in dark theme appears to be correct.

**Light OS theme:**
Screenshot 2024-01-02 at 11 38 20 AM
Screenshot 2024-01-02 at 11 39 00 AM

**Dark OS theme:**
Screenshot 2024-01-02 at 11 39 15 AM
Screenshot 2024-01-02 at 11 39 22 AM

**Review by mayank99 — COMMENTED** [review]
@FlyersPh9 Aha, good catch! Fixed in [`b0a7b5e`](https://github.com/iTwin/iTwinUI/pull/1751/commits/b0a7b5e8a33c510be3b15549da25261f75862c73)

I did initially test by changing my OS theme to light but strangely this doesn't happen in Firefox. I was able to reproduce and confirm it is fixed in Chrome after my latest commit.

**Review by FlyersPh9 — APPROVED** [review]
Looks good!

**Pull request merged**
