### PR TITLE
fix combobox disabled items behavior

### LINKED ISSUE #1201: ComboBox allows selecting disabled options but only sometimes
1. Go to https://itwin.github.io/iTwinUI/react/iframe.html?id=core-combobox--disabled-items in firefox 112 (04/11/2023)
2. Open the dropdown menu using mouse.
3. Try clicking on one of the disabled items (e.g. Algeria). It does nothing.
4. Now click on the input to focus it
5. Try using the ⬇️ arrow key to go highlight the menu items. The focus doesn't skip through disabled items but stays on the disabled items even though there is no visual indication. When pressing the <kbd>Enter</kbd>, disabled items can be selected too.

https://user-images.githubusercontent.com/9084735/231285996-72d7c96e-1dcb-442d-be12-b6f13abd8597.mov

### PR DESCRIPTION
**Pull request by mayank99**
## Changes

- Adjusted css so that disabled items have proper focus outline
- Adjusted react code so that onClickHandler will early return if the item is disabled

Both of these changes ensure that disabled items can be predictably focused but not selected. Fixes #1201 

## Testing

Tested in storybook and also in playground, both with previous version (which doesn't have ListItem changes) and with new code.

https://user-images.githubusercontent.com/9084735/231842528-de7bf044-0c21-407f-a672-16e6b05b6692.mov

## Docs

N/A

### CODE REVIEW

**Comment by LostABike** [comment]
How were you able to focus on disabled item? For testing purpose

**Comment by mayank99** [comment]
> How were you able to focus on disabled item? For testing purpose

Same as other items - using arrow keys. See the screen recording in my PR description.

I used this code in the playground:
<details>
<summary>App.tsx</summary>

```tsx
import * as React from 'react';
import { ComboBox } from '@itwin/itwinui-react';

export default () => {
  return (
    <>
      <ComboBox
        options={[
          { label: 'Apple', value: 'apple' },
          { label: 'Banana', value: 'banana' },
          { label: 'Cantaloupe', value: 'cantaloupe' },
          { label: 'Grapefruit', value: 'grapefruit', disabled: true },
          { label: 'Lychee', value: 'lychee' },
          { label: 'Kiwi', value: 'kiwi' },
          { label: 'Orange', value: 'orange', disabled: true },
          { label: 'Strawberry', value: 'strawberry' },
          { label: 'Watermelon', value: 'watermelon' },
        ]}
      />
    </>
  );
};

```
</details>

Works in [storybook](https://itwin.github.io/iTwinUI/1209/react/?path=/story/core-combobox--disabled-items) as well.

**Comment by LostABike** [comment]
> > How were you able to focus on disabled item? For testing purpose
> 
> Same as other items - using arrow keys. See the screen recording in my PR description.
> 
> I used this code in the playground:
> 
> App.tsx
> Works in [storybook](https://itwin.github.io/iTwinUI/1209/react/?path=/story/core-combobox--disabled-items) as well.

I'm not sure why I can't do that. I built your branch, also in storybook, but whenever I focus/arrow to the disabled items they just get skipped. Is there a settings I need to enable?

items

**Comment by mayank99** [comment]
i'm using firefox so that might be it.

i'll look into it. so far i notice one difference: disabled items are missing `tabindex=-1`

**Review by FlyersPh9 — APPROVED** [review]
The CSS changes look good to me, but I would wait for someone else to review the rest before merging.

**Review by LostABike — APPROVED** [review]
Yup working good for me now

**Review by gretanausedaite — APPROVED** [review]

**Pull request merged**
