### PR TITLE
feat(style): Border radius change

### PR DESCRIPTION
**Pull request by gretanausedaite**
#551 

Updated border-radius to be 4px.

### CODE REVIEW

**Comment by adamhock** [comment]
I'm a little confused on how this change fixes the artifact issue? Is it because 4px is more divisible than 3px?

**Review by veekeys — APPROVED** [review]
Looks good.
The only question, do we want to merge this into v1 or main?

**Review by adamhock — APPROVED** [review]
I believe this should be merged into main since the issue wasn't planned for v1 and this fix can potentially be released sooner

**Comment by gretanausedaite** [comment]
> I'm a little confused on how this change fixes the artifact issue? Is it because 4px is more divisible than 3px?

I'm not sure WHY this is working, but a lot of artefact or other rendering problems disappear when changed to even number of pixels (or more specifically base 2 number system). A lot of suggestions do not have explanations (eg. [this](https://stackoverflow.com/questions/12505872/3px-border-radius-has-different-look-in-ie-and-other-browsers))

My guess: It's because computer processors gets and process data in binary. This is just a guess and I did not find any info to confirm.

**Comment by gretanausedaite** [comment]
> Looks good. The only question, do we want to merge this into v1 or main?

I was thinking V1 because it's a visual change. 

I can rebase my branch and merge to main if that's better and we want to deliver this faster.

**Pull request merged**
